
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Homework 07</title>
<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/foundation.css">
<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/app.css">
<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5c65f0e01ef90f001147aa23&product=inline-share-buttons' async='async'></script>