<div class="grid-x grid-padding-x" style="margin-top: 3cm">
    <div class="large-10 cell" style="text-align: center">
        TASK NASLOV
    </div>
    <div class="large-2 cell">
        <?php if(!Session::getInstance()->isLoggedIn()): ?>
                <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>

        <?php else: ?>
                <a href="<?php echo App::config("url")?>admin/logout">Logout <?php echo Session::getInstance()->getUser()->name ?></a>
                <a href="<?php echo App::config("url")?>user/prepareedit/<?php echo Session::getInstance()->getUser()->id ?>">Edit user</a>

        <?php endif; ?>
    </div>


    <div class="large-8">

        <?php if(Session::getInstance()->isLoggedIn()):?>
                    <hr>
                    <p>
                        Ovo je logirani dio, tu staviti popis taskova koji su naslovljeni na logiranu osobu
                    </p>
                    <p>
                        neki footer, paginacija?
                    </p>
        <?php else: ?>
                <p> Ovo je dio gdje nije ulogiran</p>
                <p>- statistika zauzetosti djelatnika unutar radnog vremena<br>
                    - task (staviti koliko traje jedan task)<br>
                    - statistika koliko je odrađeno sve skupa(taskova/projekata) u nekom vremenskom razdoblju <br></p>
        <?php endif; ?>

    </div>
    <div class="large-3" style="text-align: right">

        <?php if(Session::getInstance()->getUser()->id==="1"): ?> <!-- Ovo je admin dio gdje on može pregledati usere-->
                <hr>
                <br><p>Admin menu</p>
                <a href="<?php echo App::config("url")?>admin/userslist/">User list</a><br>
                <a href="<?php echo App::config("url")?>admin/taskslist/">Task list</a><br>
                <a href="<?php echo App::config("url")?>admin/newtaskprepare/">Assign new task</a><br>
                <a href="<?php echo App::config("url")?>admin/registration">New user registration</a><br>
        <?php endif; ?>
    </div>

</div>


<?php if(!Session::getInstance()->isLoggedIn()): ?>
        <div class="large-6 column" style="text-align: left; margin-top: 1cm">
            <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>

        </div>
    <?php else: ?>
        <div class="large-12 column" style="text-align: left; margin-top: 1cm">
            <a href="<?php echo App::config("url")?>admin/logout">Logout <?php echo Session::getInstance()->getUser()->name ?></a>
        </div>
        <div class="large-12 column" style="text-align: left">
            <a href="<?php echo App::config("url")?>user/prepareedit/<?php echo Session::getInstance()->getUser()->id ?>">Edit user</a>
        </div>



    <?php endif; ?>


<!--

<br><br><br><br><br>
<h3>MAKNI POSLIJE!</h3>
<h5>taskovi:</h5>
- user moze update sam sebe - razdvoji edit user imena i user lozinke, radi uredno<br>
- ne moze obrisati niti kreirati usera - ODRAĐENO<br>
- admin moze kreirati - sve valja samo pukne kod postojećeg maila, sredi od prijašnjih primjera!! admin/register<br>
- admin može obrisati usera - pogedaj edunovu <br>
- makni sivu boju<br>
- novi task radi, promjeni iz users(id) u users(email)<br>
- riješiti listu korisnika<br>
- dodati forme statusa taska<br>
- sredi datum datetimea u importu novog taska<br>
- Kad se ulogira, pokazati opciju "prikaz profila" -> unutra uređivanje usera, pregled taskova, kreiranje novog taska
- metapodaci head facebook metadata share google!


<ul class="vertical menu align-right">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
</ul>
