<div class="grid-x grid-padding-x header">
    <?php include_once "main/headline.php"?>
    <div class="large-3 cell main" style=" text-align: center;">
        <hr>
        <?php include_once "main/menu.php"?>
    </div>
    <div class="large-9 cell main" style=" text-align: center;">
        <?php if(Session::getInstance()->isLoggedIn()):?> <!-- logiran dio -->
            <hr>
            <p>
                <h4>Check your profile for new tasks!</h4><br>
                <p class="homepageButton">Search tasks</p></a>
                <div class="grid-x">
                    <div class="large-12 columns"></div>
                    <div class="large-4 columns hide-for-small-only"></div>
                    <div class="large-4 columns small-12 columns">
                        <form class="log-in-form" method="post" action="<?php echo App::config("url")?>task/search">
                            <div class="form-group">
                                <input type="text" name="taskName" style="text-align: center;">
                            </div>
                            <p class="register"><button type="submit" class="register">Search</button></p>
                        </form>
                    </div>
                </div>
            </p>
        <?php else: ?>
            <hr>
            <p> <h2>Welcome!</h2></p>
            <p> <h4>Log in to see your tasks</h4>
                <h4>or</h4>
            <a href="<?php echo App::config("url")?>task/publicTasks/"><p class="homepageButton">See statistics</p></a>

            <br>

        <?php endif; ?>
    </div>
    </div>
</div>


<!--


<br><br><br><br><br>
<h3>MAKNI POSLIJE!</h3>
<h5>taskovi:</h5>
- user moze update sam sebe - razdvoji edit user imena i user lozinke, radi uredno<br>
- ne moze obrisati niti kreirati usera - ODRAĐENO<br>
- admin moze kreirati - sve valja samo pukne kod postojećeg maila, sredi od prijašnjih primjera!! admin/register<br>
- admin može obrisati usera - pogedaj edunovu <br>
- makni sivu boju<br>
- novi task radi, promjeni iz users(id) u users(email)<br>
- riješiti listu korisnika<br>
- dodati forme statusa taska<br>
- sredi datum datetimea u importu novog taska<br>
- Kad se ulogira, pokazati opciju "prikaz profila" -> unutra uređivanje usera, pregled taskova, kreiranje novog taska
- metapodaci head facebook metadata share google!


<ul class="vertical menu align-right">
    <li><a href="#">One</a></li>
    <li><a href="#">Two</a></li>
    <li><a href="#">Three</a></li>
    <li><a href="#">Four</a></li>
</ul>
