
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
    <head>
        <?php include_once "head.phtml"?>
    </head>
    <body class="body1">
        <div id="fb-root"></div>
        <div class="grid-container">
            <div class="12-large columns hide-for-small-only" style="margin-top: 2cm"></div>
        </div>
        <div class="grid-container">

            <div>
                <?php echo $content ?>
            </div>
        </div>
        <?php include_once "skripte.phtml"?>
    </body>
</html>
