
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
    <head>
        <?php include_once "head.phtml"?>
    </head>
    <body>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src ='https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.0&appId=1774450775918270&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>


    <div class="grid-container">
            <div class="grid-x grid-padding-x">
                <div class="large-12 cell">
                    <?php echo $content ?>
                </div>
            </div>
        </div>
        <?php include_once "skripte.phtml"?>
    </body>
</html>
