


<form method="post" action="<?php echo App::config('url') ?>admin/register">

    <div class="form-group">
        <label for="firstname">First name</label>
        <input type="firstname" name="firstName">

        <label for="lastname">Last name</label>
        <input type="lastname" name="lastName">

        <label for="email">Email</label>
        <input type="email" name="email">

        <label for="password">Password</label>
        <input type="password" name="password">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>
    <a href="<?php echo App::config('url') ?>">Cancel</a>

</form>
