<?php
/**
 * Created by PhpStorm.
 * User: ipa
 * Date: 21.02.19.
 * Time: 17:14
 */
// Tu se trebaju prikazati svi useri

echo "novi taskovi"."<hr>";

?>

<form method="post" action="<?php echo App::config('url') ?>admin/newtask">

    <div class="form-group">
        <label for="Task name">Task name</label>
        <input type="text" name="taskName">

        <label for="User">User </label>
        <input type="number" name="users">

        <label for="Task start date">Task start date</label>
        <input type="datetime" name="taskStartTime">

        <label for="Task end date">Task end date</label>
        <input type="datetime" name="taskEndTime">

        <label for="Task description">Task description</label>
        <input type="text" name="taskDescription">

        <label for="Task status">Task status</label>
        <input type="text" name="taskStatus">

        <label for="Task category">Task category</label>
        <input type="text" name="taskCategory">
    </div>

    <button type="submit" class="btn btn-primary">Add new task</button>
    <a href="<?php echo App::config('url') ?>">Cancel</a>

</form>
<?php echo "pogledaj registraciju novih usera i prilagodi";
?>



<!-- id, taskname, users(id), taskStartTime, taskEndTime, taskDescription, taskStatus, taskCategory