<div class="grid-x grid-padding-x header" xmlns="http://www.w3.org/1999/html">
    <div class="large-12 columns" style="height: 1rem"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns headerBackButton small-12 columns">
        <a href="<?php echo App::config('url') ?>"><p class="backButton">Back to homepage</p></a>
    </div>
    <div class="large-1 columns"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns small-12">
        <div class="grid-x">
            <div class="large-4 medium-4 hide-for-small-only"></div>
            <div class="large-4 medium-4 small-12 columns">
                <?php if(Session::getInstance()->isLoggedIn()):?>
                    <form method="post" action="<?php echo App::config('url') ?>task/newtask">
                        <p class="backButton">Create new task</p>
                        <div class="form-group">

                            <p class="register"><label for="Task name">Task name</label></p>
                            <input type="text" name="taskName" style="text-align: center;">
                            <?php if(Session::getInstance()->isLoggedIn()&&Session::getInstance()->getUser()->id==="1"): ?>
                                <p class="register"><label for="email">Asign user</label></p>
                                <input list="email" name="email">
                                <datalist id="email">
                                    <?php foreach ($findUserEmail as $email): ?>
                                        <option value="<?=$email->email?>">
                                    <?php endforeach; ?>
                                </datalist>
                            <?php else:?>
                            <p class="register"><label for="email">Asign user</label></p>
                            <input list="email" name="email">
                            <datalist id="email">

                                <option value="<?=$findCurrentUser->email?>">

                            </datalist>
                            <?php endif; ?>

                            <p class="register"><label for="Task start date">Task duration time(h)</label></p>
                            <input type="number" name="taskTimeNeed" style="text-align: center;">

                            <p class="register"><label for="Task end date">Task end date</label></p>
                            <input id="datefield" name="taskEndTime" type='date' data-date-format="YYYY-MM-DD"  min='1899-01-01' max='2000-13-13' style="text-align: center;"/>

                            <p class="register"><label for="Task description">Task description</label></p>
                            <input type="text" name="taskDescription" style="text-align: center;">

                            <p class="register"><label for="Task category">Task category </label></p>
                            <input list="category" name="category">
                            <datalist id="category">
                                <option value="Administration">
                                <option value="Marketing">
                                <option value="Design">
                                <option value="Front end">
                                <option value="Back end">
                                <option value="Testing">
                            </datalist>

                            <p class="register"><label for="Tag name">add tags</label></p>
                            <input type="text" name="tagName" style="text-align: center;">
                            <p class="register"><button type="submit" class="register">Done</button></p>


                        </div>
                    </form>
                <?php endif; ?>
            </div>
            <div class="large-4 medium-4 hide-for-small-only"></div>
        </div>
    </div>
    <div class="large-1 columns"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns headerBackButton small-12 columns">
        <a href="<?php echo App::config('url') ?>"><p class="backButton">Back to homepage</p></a>
    </div>
    <div class="large-1 columns"></div>
</div>

