<?php

require "fpdf.php";
$pdf = new FPDF('P','mm','A4');
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->write(20,"Task name: $message->taskName \n");
$pdf->write(20,"Assigned user: $email->email\n");
$pdf->write(20,"Task time need: $message->taskTimeNeed (h)\n");
$pdf->write(20,"Task deadline: $message->taskEndTime\n");
$pdf->write(20,"Task description: $message->taskDescription\n");
$pdf->write(20,"Task status: $message->taskStatus\n");
$pdf->write(20,"Task category: $message->taskCategory\n");
$pdf->Output();
//var_dump($message);
?>


