<div class="grid-x grid-padding-x header" xmlns="http://www.w3.org/1999/html">
    <div class="large-12 columns" style="height: 1rem"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns headerBackButton small-12 columns">
        <a href="<?php echo App::config('url') ?>"><p class="backButton">Back to homepage</p></a>
    </div>
    <div class="large-1 columns"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns small-12">
        <div class="grid-x">
            <div class="large-4 medium-4 hide-for-small-only"></div>
            <div class="large-4 medium-4 small-12 columns">
                <?php if(Session::getInstance()->isLoggedIn()):?>
                    <form class="log-in-form" method="post" action="<?php echo App::config("url")?>user/editpassword/<?php echo Session::getInstance()->getUser()->id ?>">
                        <?= $message ?>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password">

                            <label for="password">Confirm password</label>
                            <input type="password" name="confirmpassword">
                        </div>
                        <p class="register"><button type="submit" class="register">Update</button></p>
                    </form>

                <?php endif; ?>
            </div>
            <div class="large-4 medium-4 hide-for-small-only"></div>
        </div>
    </div>
    <div class="large-1 columns"></div>
    <div class="large-1 columns"></div>
    <div class="large-10 columns headerBackButton small-12 columns">
        <a href="<?php echo App::config('url') ?>"><p class="backButton">Back to homepage</p></a>
    </div>
    <div class="large-1 columns"></div>
</div>




















